title: Reked
logo: images/logo.svg
description: Minimalistic Theme for Jekyll
baseurl: ''
url: ''
author:
  name: Sasha Levi
  bio: >-
    Hi, my name is Sasha Levi. I like being at the center of events, being free
    and enjoying every moment. Thank you for visiting my blog.
twitter: 'https://twitter.com/'
facebook: 'https://facebook.com/'
dribbble: 'https://dribbble.com/'
instagram: 'https://instagram.com/'
pinterest: 'https://pinterest.com/'
email: forexample@website.com
hero: true
hero-title: Raked Minimalistic Theme
hero-subtitle: For those who love simplicity
hero-image: images/14.jpg
footer-image: images/14.jpg
disqus-identifier: mr-brown
google-analytics: ''
mailchimp: ''
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
paginate: 4
paginate_path: '/page/:num'
defaults:
  - scope:
      path: _pages
    values:
      permalink: '/:basename:output_ext'
include:
  - _pages
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty
sass:
  sass_dir: _sass
  style: compressed
